name: EvenMoreFish-KioCG
author: Oheers
version: ${project.version}
main: com.oheers.fish.EvenMoreFish
api-version: 1.16
depend: [ Vault ]
softdepend: [ WorldGuard, PlaceholderAPI, RedProtect, mcMMO, AureliumSkills, ItemsAdder ]
loadbefore: [ AntiAC ]

commands:
  evenmorefish:
    usage: /<command> [name]
    aliases: [ emf ]
    permission: emf.command
libraries:
  - com.zaxxer:HikariCP:${hikaricp.version}
  - org.flywaydb:flyway-core:${flyway.version}
  - com.github.ben-manes.caffeine:caffeine:${caffiene.version}





#  There are roughly 300-400 moose roaming freely in the woods of Sweden
